FROM golang:1.22-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go version
RUN echo "---- go.mod ----" && sed -n '1,40p' go.mod
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/modbus-server .

FROM alpine:3.20

WORKDIR /app

COPY --from=build /out/modbus-server /app/modbus-server
RUN chmod +x /app/modbus-server

EXPOSE 8080

CMD ["/app/modbus-server"]